name: SimpleChatChannels
main: me.odium.simplechatchannels.Loader
version: 0.7.7
description: Simple Chat Channels
commands:
   scc:
      aliases: [SimpleChatChannels]
      description: SimpleChatChannels Main Menu
      permission:
      usage: /scc
   addchan:
      description: Create a Channel
      permission: scc.addchan
      usage: /addchan <channelname>
   delchan:
      description: Delete a Channel
      permission:
      usage: /delchan <channelname>
   joinchan:
      description: Join an unlocked channel
      permission: scc.join
      usage: /joinchan <channelname>
   partchan:
      aliases: [leavechan]
      description: Part the channel you're in
      permission: scc.join
      usage: /partchan <channelname>
   kuser:
      description: kick a user from a channel
      permission:
      usage: /kuser <channelname> <playername>
   adduser:
      description: Add a user to a locked channel
      permission:
      usage: /adduser <channelname> <playername>
   deluser:
      description: Del a user from a locked channel
      permission:
      usage: /deluser <channelname> <playername>
   addowner:
      description: Add an owner to a channel you own
      permission:
      usage: /addowner <channelname> <playername>
   delowner:
      description: delete an owner to a channel you own
      permission:
      usage: /delowner <channelname> <playername>
   chanlist:
      aliases: [channels]
      description: Channels List
      permission: scc.chanlist
      usage: /chanlist [channelname] [owner/access]
   topic:
      description: Set a channel topic
      permission:
      usage: /topic <channelname> <topic>
   spychan:
      description: Spy on specific/all channel conversation
      permission: scc.spychan
      usage: /spychan [channelname]